source "https://rubygems.org/"

gem 'async-dns'
gem 'brotli'
gem 'chronic'
gem 'console'
gem 'falcon'
gem 'foreman'
gem 'icalendar'
gem 'linkeddata'
gem 'mail'
gem 'nokogiri'
gem 'org-ruby'
gem 'redcarpet'
gem 'rouge'
gem 'ruby-net-text'
gem 'taglib-ruby'
