# coding: utf-8
class WebResource
    module HTML

      # URI -> emoji

      Icons = {
      'ArticleGQL' => '📝',
      'article' => '📰',
      'sioct:Comment' => '🗨️',
      'uri' => '🌍',
      Abstract => '✍',
      Audio => '🔊',
      Content => '',
      Creator => '👤',
      DC + 'hasFormat' => '≈',
      DC + 'identifier' => '☸',
      DC + 'language' => '👅',
      DC + 'rights' => '⚖️',
      DOAP+'license' => '⚖️',
      Date => '⌚', 'http://purl.org/dc/terms/created' => '⌚', 'http://purl.org/dc/terms/modified' => '⌚',
      FOAF + 'Document' => '📄',
      FOAF + 'Image' => '🖼️',
      FOAF + 'name' => '📛',
      Image => '🖼️',
      LDP + 'Container' => '📁',
      LDP + 'contains' => '📁',
      LDP + 'next' => '▶',
      LDP + 'prev' => '◀',
      LDP + 'up' => '▲',
      Link => '☛',
      Post => '📝',
      RDFs + 'label' => '🏷',
      RDFs + 'subClassOf' => '⊂',
      Resource => '🌐',
      SIOC + 'BlogPost' => '📝',
      SIOC + 'BoardPost' => '📝',
      SIOC + 'InstantMessage' => '🐦',
      SIOC + 'MailMessage' => '✉️',
      SIOC + 'MicroPost' => '🐦',
      SIOC + 'UserAccount' => '👤',
      SIOC + 'attachment' => '✉',
      SIOC + 'has_discussion' => '🗨️',
      SIOC + 'reply_of' => '↩',
      SIOC + 'richContent' => '',
      SKOS + 'Concept' => '🧠',
      Schema + 'AggregateOffer' => '🏷',
      Schema + 'AggregateRating' => '🎖',
      Schema + 'BreadcrumbList' => '☰',
      Schema + 'CommentAction' => '🗨️',
      Schema + 'DiscussionForumPosting' => '📝',
      Schema + 'FollowAction' => '☑️',
      Schema + 'GeoCoordinates' => '🗺',
      Schema + 'ImageObject' => '🖼️',
      Schema + 'LikeAction' => '👍',
      Schema + 'ListItem' => '☰',
      Schema + 'LocalBusiness' => '🏪',
      Schema + 'MenuItem' => '🍽',
      Schema + 'MusicRecording' => '💿',
      Schema + 'MusicRelease' => '🎵',
      Schema + 'Offer' => '🏷',
      Schema + 'Organization' => '👥',
      Schema + 'Person' => '👤',
      Schema + 'PostalAddress' => '🗺',
      Schema + 'Product' => '🛍',
      Schema + 'Question' => '❓',
      Schema + 'SearchAction' => '🔎',
      Schema + 'SearchResult' => '🔍',
      Schema + 'ShareAction' => '🎒',
      Schema + 'SiteNavigationElement' => '⎈',
      Schema + 'WebPage' => '📃',
      Schema + 'WebSite' => '🌐',
      Schema + 'aggregateRating' => '🎖',
      Schema + 'authToken' => '🔑',
      Schema + 'availability' => '💲',
      Schema + 'brand' => '®',
      Schema + 'color' => '🎨',
      Schema + 'commentCount' => '🗯',
      Schema + 'contentType' => '🧱',
      Schema + 'copyrightNotice' => '©',
      Schema + 'downloadCount' => '⬇️',
      Schema + 'duration' => '⏱️',
      Schema + 'faxNumber' => '📠',
      Schema + 'hasMenuItem' => '☰',
      Schema + 'height' => '↕',
      Schema + 'interactionCount' => '📈',
      Schema + 'interactionStatistic' => '📈',
      Schema + 'isFamilyFriendly' => '👩‍👩‍👦',
      Schema + 'itemListElement' => '☰',
      Schema + 'latitude' => '📍',
      Schema + 'locale' => '🗺',
      Schema + 'location' => '🗺',
      Schema + 'longitude' => '📍',
      Schema + 'mainEntityOfPage' => '🥩',
      Schema + 'maxPrice' => '≤',
      Schema + 'minPrice' => '≥',
      Schema + 'nextItem' => '▶',
      Schema + 'playCount' => '🎶',
      Schema + 'prepTime' => '⏱️',
      Schema + 'previousItem' => '◀',
      Schema + 'price' => '💲',
      Schema + 'priceCurrency' => '💱',
      Schema + 'publisher' => '🏢',
      Schema + 'rating' => '🎖',
      Schema + 'reviewRating' => '🎖',
      Schema + 'sameAs' => '=',
      Schema + 'size' => '⚖',
      Schema + 'streetAddress' => '📍',
      Schema + 'telephone' => '📞',
      Schema + 'upvoteCount' => '👍',
      Schema + 'views' => '👀',
      Schema + 'width' => '↔',
      Schemas + 'CommentAction' => '🗨️',
      Schemas+ 'BreadcrumbList' => '☰',
      Schemas+ 'Person' => '👤',
      Schemas+ 'commentCount' => '🗯',
      Schemas+ 'itemListElement' => '☰',
      Schemas+ 'repostCount' => '⏩',
      Schemas+ 'upvoteCount' => '👍',
      Stat + 'File' => '📄',
      To => '☇',
      Type => '📕',
      Video => '🎞',
    }

  end
end
